---
title: "RE methylation cluster and immune data"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">

.figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

```{r library, echo = FALSE}
library(tidyverse)
library(labelled)
# library(REMP)
# library(ComplexHeatmap)
library(gtsummary)
library(survival)
library(survminer)
theme_gtsummary_compact()
theme_set(theme_classic())
```

<style>
div.darkblue { background-color:#0099CC; border-radius: 5px; padding: 20px; font-size: 38px}
</style>
<div class = "blue">

<span style="color: white;">RE methylation cluster and HiTIMED data</span>

</div>
<br>

```{r load}
load(paste0(here::here(), "/cleaned_07082022.rda"))

cluster_res_list <- read_rds(paste0(here::here(), "/clustering/MOVICS/movics_cluster_res_list_08032023.rds"))

L1_imputed <- read_rds(paste0(here::here(), "/L1_imputed.rds"))
Alu_imputed <- read_rds(paste0(here::here(), "/Alu_imputed.rds"))
ERV_imputed <- read_rds(paste0(here::here(), "/ERV_imputed.rds"))

met_data <- read_rds(paste0(here::here(), "/met_data_01-23-2025.rds"))

hit_data <- readxl::read_xlsx(paste0(here::here(), "/HiTIMED_round.xlsx"))
```

```{r join HIT}
met_data <- left_join(met_data, hit_data, by = c("patient_id" = "Complete.Barcode")) %>% 
  mutate(CD4 = CD4mem + CD4nv) %>% 
  mutate(CD8 = CD8mem + CD8nv)
```












```{r Labeling}
var_label(met_data) <- list(refage = "Age at diagnosis",
                            stage_cat = "Stage",
                            debulking_CA125 = "Debulking Status", 
                            neoadjuvant = "Neoadjuvant chemotherapy",
                            adjuvant = "Adjuvant chemotherapy",
                            smokcurrent = "Current smoking status",
                            germline_mutation_BRCA1 = "BRCA1 germline carrier", 
                            germline_mutation_BRCA2 = "BRCA2 germline carrier", 
                            tumor_mutation_BRCA1 = "BRCA1 tumor carrier", 
                            tumor_mutation_BRCA2 = "BRCA2 tumor carrier",
                            germline_mutation_TP53 = "TP53 germline carrier", 
                            tumor_mutation_TP53 = "TP53 tumor carrier",
                            pathogenic_germline_BRCA1 = "pathogenic BRCA1 germline carrier", 
                            pathogenic_germline_BRCA2 = "pathogenic BRCA2 germline carrier",
                            pathogenic_tumor_BRCA1 = "pathogenic BRCA1 tumor carrier", 
                            pathogenic_tumor_BRCA2 = "pathogenic BRCA2 tumor carrier",
                            pathogenic_germline_TP53 = "pathogenic TP53 germline carrier", 
                            pathogenic_tumor_TP53 = "pathogenic TP53 tumor carrier",
                            coca_RE_cluster = "COCA cluster")
```

# I. Table 1. Patient characteristics overall
```{r}
met_data %>% 
  select(Tumor : CD8nv, CD4, CD8,
         coca_RE_cluster
  ) %>% 
  tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
              type = list(c(CD4nv) ~ "continuous")#,
              # digits = list(all_continuous() ~ 1)
              ) %>%
  bold_labels() %>% add_stat_label() %>%
  modify_header(list(label ~ "**Patient characteristics**", 
                     all_stat_cols() ~ "**{level}**, N = {n}"))
```
<br>
<br>

# II. Table 2. Patient characteristics by cluster
```{r}
met_data %>% 
  select(Tumor : CD8nv, CD4, CD8,
         coca_RE_cluster
  ) %>% 
  tbl_summary(by = coca_RE_cluster,
              statistic = list(all_continuous() ~ "{mean} ({sd})"),
              type = list(c(CD4nv) ~ "continuous")#,
              # digits = list(all_continuous() ~ 1)
              ) %>%
  bold_labels() %>% add_stat_label() %>% 
  add_p() %>% bold_p(t=.05) %>% add_overall() %>% 
  modify_spanning_header(c(stat_1, stat_2) ~ "COCA cluster") %>% 
  modify_header(list(label ~ "**Patient characteristics**"))
```

```{r}
met_data %>% 
  ggplot(aes(x = CD8mem, fill = coca_RE_cluster))+
  geom_histogram()

met_data %>% 
  ggplot(aes(x = CD8nv, fill = coca_RE_cluster))+
  geom_histogram()

met_data %>% 
  ggplot(aes(x = CD8mem, fill = coca_RE_cluster))+
  geom_density(alpha = 0.5)

met_data %>% 
  ggplot(aes(x = CD8nv, fill = coca_RE_cluster))+
  geom_density(alpha = 0.5)

met_data %>% 
  ggplot(aes(x = CD4, fill = coca_RE_cluster))+
  geom_density(alpha = 0.5)

met_data %>% 
  ggplot(aes(x = CD8, fill = coca_RE_cluster))+
  geom_density(alpha = 0.5)
```













